### ISSUE TITLE
Let's talk heating...

### ISSUE THREAD

**Issue by dandancheeseandham** [railcore/configs#24]
Since the Duet has the ability to auto tune heaters, I'm thinking there would there be an efficiency, safety and print quality benefit in removing the existing heater model of Tony's, and providing direction and macros to tune the heater (which would be unique for their combination of equipment i.e. hotend, fan, heater, cooling block and environment)

https://duet3d.dozuki.com/Wiki/Tuning_the_heater_temperature_control

The Duet stores the parameters in config-override.g and I guess in theory the heaters would be running at their best with this enabled.

Thoughts?

**Comment by JohnOCFII** [comment]
Well, personally I'd like to try it.  If it works for us, we should see about including it.

**Comment by lostapathy** [comment]
I agree - I think so long as we have clear directions on how to set it up, we should setup this configuration to be the "ideal" railcore config.

**Comment by kraegar** [comment]
PID tuning your heaters is recommended in the docs.  Whether you use
config-override.g or not is a matter of preference.  The lines in the
config are just starting points, and *everyone* should absolutely be tuning
their bed & hotends.  (If you didn't, you skipped that bit of the doc ;) )

**Comment by dandancheeseandham** [comment]
This is my reasoning - if everyone should be tuning, then the parameters for the heaters should not be there, in order to protect people that have missed or skipped that part of the build documentation.

I'll propose a patch shortly.

**Comment by kraegar** [comment]
You want *something* there as a starting point for the hotend.

**Comment by dandancheeseandham** [comment]
IMHO a heater model has no place to be there, if "**everyone** should absolutely be tuning their bed & hotends" and the guide has a section on it. Also,

 * if there is a heater model, some people will think it's sorted out and/or miss it in the guide.
 * with no M501 in the config.g, some newer users may do figure out to do some tuning, save results but not realise they won't take effect.
 * others may try to take the output of M307 H1 and spend unnecessary time trying to fit it into the existing M307 command manually.

The Duet3D documentation says "After power up or reset, the bed heater controller is in bang-bang mode and the extruder heaters use the model-derived PID parameters"

I've just done a test and without an explicit M307 and it defaulted to
M307 H1 A340.0 C140.0 D5.5 B0 S1.0

which isn't too different to the existing one in config.g, which is
M307 H1 A270.7 C90.4 D6.7 B0 S1.0

**Comment by dandancheeseandham** [comment]
I'll close this and further discussion(which I feel is necessary) can be within the PR.
https://github.com/railcore/configs/pull/25
