### ISSUE TITLE
New parts/models repository problem.

### ISSUE THREAD

**Issue by dandancheeseandham** [railcore/configs#27]
So it was suggested to have a new repository for parts yesterday in #railcore , a handy one stop shop with stl's for 3D printed parts and dxf's (and perhaps pdf's as my laser cutter preferred that format) for cutting the panels

I was just about to create it  when I noticed there is no [CC BY 3.0](https://creativecommons.org/licenses/by/3.0/) which @kraegar has put the RailCore project under on Thingiverse. So we have a license issue.
Github only offers these [licenses](https://choosealicense.com/licenses/)

Naturally, I can't just place Tony's STL's in a repo with a different license. I also do not understand the ramifications of having two different places with different licenses (even if blessed by Tony and vaguely compatible).

Since I do not have the authority to modify the license or actually understand this, I'm not creating the parts repository. 
I'll need some input here.

**Comment by JohnOCFII** [comment]
It looks like the mechanics of adding a CC BY 3.0 (or other license) is described here: https://github.com/github/choosealicense.com#license

More info here: https://choosealicense.com/non-software/

**Comment by natewalck** [comment]
What @JohnOCFII said. If you place a copy of the license affording to the rules of that license, it applied to whatever is in the repo.
