### ISSUE TITLE
Cleanup

### ISSUE THREAD

**Issue by dandancheeseandham** [railcore/configs#50]
Time for a cleanup.

i) Removing the Duet Archive. I feel is fairly safe now. Just the Project R3D files need to be addressed.

ii) Klipper. If no one is maintaining it, perhaps it should either go, or at the very least be nested away in a "not maintained" section?

My thoughts are 
Create a "unmaintained" folder to put in the P.R3D stuff (and perhaps Klipper if people think it's important enough to keep)
Duet archive should be deleted.

**Comment by natewalck** [comment]
1. Agree
2. Lets put Klipper into unmaintained along with P.R3D stuff
