### ISSUE TITLE
Low jerk in examples

### ISSUE THREAD

**Issue by JohnOCFII** [railcore/configs#76]
All the example configs as well as the unmaintained configs still have the really low E20 jerk setting that does not play well with Pressure advance.

For comparison, this is what I use in my config.g

M566 X1000 Y1000 Z80 E3600             			    ; Set maximum instantaneous (jerk) speed changes (mm/min)
M201 X1750 Y1750 Z20 E1500                          ; Set accelerations (mm/s^2)

**Comment by dandancheeseandham** [comment]
Do you mean https://github.com/railcore/configs/pull/70 ?
I'll just merge it then.
